name: distribu-town
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - grpcio==1.60.0
    - grpcio-tools==1.60.0
    - protobuf==4.25.1
    - flask==3.0.0
    - requests==2.31.0
    - numpy==1.24.3
    - matplotlib==3.7.1

